CREATE TABLE [dbo].[ShoppingList]
(
	[ShoppingListID] INT NOT NULL PRIMARY KEY, 
    [ShoppingListName] NVARCHAR(64) NOT NULL UNIQUE,
	[CreatedOn] DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	[UpdatedOn] DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())
)
