//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS560_RecipeManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIS560_RecipeManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///AAA
        ///AAAS
        ///aardvark
        ///Aarhus
        ///Aaron
        ///ABA
        ///Ababa
        ///aback
        ///abacus
        ///abalone
        ///abandon
        ///abase
        ///abash
        ///abate
        ///abbas
        ///abbe
        ///abbey
        ///abbot
        ///Abbott
        ///abbreviate
        ///abc
        ///abdicate
        ///abdomen
        ///abdominal
        ///abduct
        ///Abe
        ///abed
        ///Abel
        ///Abelian
        ///Abelson
        ///Aberdeen
        ///Abernathy
        ///aberrant
        ///aberrate
        ///abet
        ///abetted
        ///abetting
        ///abeyance
        ///abeyant
        ///abhor
        ///abhorred
        ///abhorrent
        ///abide
        ///Abidjan
        ///Abigail
        ///abject
        ///abjure
        ///ablate
        ///ablaze
        ///able
        ///ablution
        ///abnegation
        ///Abner
        ///abnormal
        ///Abo
        ///aboard
        ///abode
        ///abolish
        ///abolition
        ///abominable
        ///abominate
        ///abor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wordlist {
            get {
                return ResourceManager.GetString("wordlist", resourceCulture);
            }
        }
    }
}
